Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 60
      MemorySize: 512
      Handler: com.example.skeleton.StreamLambdaHandler::handleRequest
      CodeUri: ..
      Runtime: java17